version: '3.8'

services:
  db:
    image: postgres:14.3
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=HexImages_User
      - POSTGRES_PASSWORD=HexImages_Password
      - POSTGRES_DB=HexImages_DB
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./heximages/:/usr/src/heximages/
    ports:
      - 8000:8000
    env_file:
      - ./.env.dev
    depends_on:
      - db

volumes:
  postgres_data:
    