version: '3.8'

services:
  db:
    image: postgres:14.3
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env.prod.db
  web:
    build:
      context: .
      dockerfile: Dockerfile.prod
    command: gunicorn heximages.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - static_volume:/home/heximages/web/staticfiles
      - media_volume:/home/heximages/web/mediafiles
    expose:
      - 8000
    environment:
      - MEDIAFILES_DIR=mediafiles
    env_file:
      - ./.env.prod
    depends_on:
      - db
  nginx:
    build: ./nginx
    volumes:
      - static_volume:/home/heximages/web/staticfiles
      - media_volume:/home/heximages/web/mediafiles
    ports:
      - 8032:80
    depends_on:
      - web

volumes:
  postgres_data:
  static_volume:
  media_volume: